### ISSUE TITLE
Consider upgrading peerDependency for es6-shim

### ISSUE THREAD

**Issue by acr92** [radify/karma-es6-shim#4]
[es6-shim has been released in version 0.33.0](https://www.npmjs.com/package/es6-shim), however when I tried to install this karma-es6-shim:

```
npm ERR! peerinvalid The package es6-shim does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-es6-shim@0.1.3 wants es6-shim@~0.28.1
```

**Comment by jfmercer** [comment]
@Blystad. Thanks for pointing this out. Much appreciated. #5 fixed this. Issue closed.

**Comment by nateabele** [comment]
We may have to re-open this, since one of the main purposes (apparently) of this project was the use of peer dependencies. @gavD Can you weigh in on that?

**Comment by acr92** [comment]
If the peer dependency was configured to be more lenient then it wouldn't be a problem.

**Comment by jfmercer** [comment]
I found this in the [README](https://github.com/radify/karma-es6-shim/blob/master/README.md):

_Therefore, we have modified [pokehanai/karma-es5-shim](https://github.com/pokehanai/karma-es5-shim) in the following ways:_
- **Use peerDependencies rather than submodules**
- _Include both ES5 and ES6 so that PhantomJS can run tests_

I didn't see that bit about peerDependencies before. I think we'll need to reopen, but I'll wait for @gavD's opinion.

@Blystad How would you make the peer dependencies more lenient?

**Comment by acr92** [comment]
Ref: http://blog.nodejs.org/2013/02/07/peer-dependencies/

Maybe something like: 

`>= 0.28.1`

and if something breaks in the future, one could limit it.
